colourful: true

filekinds:
  normal: { foreground: "#ebdbb2" }
  directory: { foreground: "#83a598" }
  symlink: { foreground: "#8ec07c" }
  pipe: { foreground: "#928374" }
  block_device: { foreground: "#d79921" }
  char_device: { foreground: "#d79921" }
  socket: { foreground: "#928374" }
  special: { foreground: "#d3869b" }
  executable: { foreground: "#b8bb26" }
  mount_point: { foreground: "#8ec07c" }

perms:
  user_read: { foreground: "#8ec07c" }
  user_write: { foreground: "#d3869b" }
  user_execute_file: { foreground: "#b8bb26" }
  user_execute_other: { foreground: "#b8bb26" }
  group_read: { foreground: "#8ec07c" }
  group_write: { foreground: "#fe8019" }
  group_execute: { foreground: "#b8bb26" }
  other_read: { foreground: "#8ec07c" }
  other_write: { foreground: "#fb4934" }
  other_execute: { foreground: "#b8bb26" }
  special_user_file: { foreground: "#fb4934" }
  special_other: { foreground: "#cc241d" }
  attribute: { foreground: "#928374" }

size:
  major: { foreground: "#8ec07c" }
  minor: { foreground: "#d3869b" }
  number_byte: { foreground: "#ebdbb2" }
  number_kilo: { foreground: "#83a598" }
  number_mega: { foreground: "#8ec07c" }
  number_giga: { foreground: "#fe8019" }
  number_huge: { foreground: "#fb4934" }
  unit_byte: { foreground: "#ebdbb2" }
  unit_kilo: { foreground: "#83a598" }
  unit_mega: { foreground: "#8ec07c" }
  unit_giga: { foreground: "#fe8019" }
  unit_huge: { foreground: "#fb4934" }

users:
  user_you: { foreground: "#458588" }
  user_root: { foreground: "#d3869b" }
  user_other: { foreground: "#8ec07c" }
  group_yours: { foreground: "#83a598" }
  group_root: { foreground: "#d3869b" }
  group_other: { foreground: "#ebdbb2" }

links:
  normal: { foreground: "#83a598" }
  multi_link_file: { foreground: "#8ec07c" }

git:
  new: { foreground: "#b8bb26" }
  modified: { foreground: "#d3869b" }
  deleted: { foreground: "#cc241d" }
  renamed: { foreground: "#8ec07c" }
  typechange: { foreground: "#8ec07c" }
  ignored: { foreground: "#928374" }
  conflicted: { foreground: "#fe8019" }

git_repo:
  branch_main: { foreground: "#928374" }
  branch_other: { foreground: "#8ec07c" }
  git_clean: { foreground: "#282828" }
  git_dirty: { foreground: "#d3869b" }

security_context:
  colon: { foreground: "#928374" }
  user: { foreground: "#928374" }
  role: { foreground: "#8ec07c" }
  typ: { foreground: "#458588" }
  range: { foreground: "#d3869b" }

file_type:
  image: { foreground: "#83a598" }
  video: { foreground: "#8ec07c" }
  music: { foreground: "#689d6a" }
  lossless: { foreground: "#458588" }
  crypto: { foreground: "#cc241d" }
  document: { foreground: "#ebdbb2" }
  compressed: { foreground: "#fe8019" }
  temp: { foreground: "#928374" }
  compiled: { foreground: "#928374" }
  build: { foreground: "#8ec07c" }
  source: { foreground: "#d3869b" }

punctuation: { foreground: "#282828" }
date: { foreground: "#d79921" }
inode: { foreground: "#928374" }
blocks: { foreground: "#928374" }
header: { foreground: "#ebdbb2" }
octal: { foreground: "#fe8019" }
flags: { foreground: "#d3869b" }

symlink_path: { foreground: "#83a598" }
control_char: { foreground: "#fe8019" }
broken_symlink: { foreground: "#fb4934" }
broken_path_overlay: { foreground: "#fb4934" }
