lastupdatecheck: 1721207402
recentrepos:
    - /Users/Adrien/workspace/adrmo
    - /Users/Adrien/workspace/code/centreon
    - /Users/Adrien/workspace/code/centreon-modules
    - /Users/Adrien/workspace/centreon-dev-environment
    - /Users/Adrien/.local/share/nvim/lazy/phpactor.nvim
    - /Users/Adrien/.local/share/nvim/lazy/kulala.nvim
    - /Users/Adrien/workspace/code/centreon-test-lib
    - /Users/Adrien/.local/share/nvim/lazy/telescope-fzf-native.nvim
    - /Users/Adrien/.local/share/nvim/lazy/friendly-snippets
startuppopupversion: 5
lastversion: 0.44.1
customcommandshistory:
    - q
    - git cherry-pick --continue
    - q!
    - git checkout develop
hidecommandlog: true
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
